server:
  port: 8000  

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegister: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server


